sonar.projectKey=so-why-pikachu_Emo-Judge-Agent
sonar.organization=so-why-pikachu

sonar.projectName=Emo Judge Agent
sonar.projectVersion=1.0

sonar.sources=backend/src/main,frontend
sonar.tests=backend/src/test

sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/target/**,**/.git/**

sonar.java.binaries=backend/target/classes
sonar.sourceEncoding=UTF-8
sonar.qualitygate.wait=true
