server:
  port: 8081

  # spring:
  #   datasource:
  #     url: jdbc:sqlite:./data/emoagent.sqlite3
  #     driver-class-name: org.sqlite.JDBC

  #   jpa:
  #     database-platform: org.hibernate.community.dialect.SQLiteDialect
  #     hibernate:
  #       ddl-auto: update
  #     show-sql: false

spring:
  config:
    import: optional:file:F:/emotional_agent/database/.env[.properties]

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/emotion_agent?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false

  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

emo-agent:
  base-url: http://127.0.0.1:8000
